apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-auth
    spec:
      containers:
      - name: weatherapp-auth
        image: amgadashraf/weatherauth:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysqlserv
          - name: DB_USER
            value: authuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: auth-password
          - name: DB_NAME
            value: weatherapp
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sqlsecret
                key: secret-key